### ISSUE TITLE
Dosen't allow config editing

### ISSUE THREAD

**Issue by DinoNuggets2** [joker-119/SCP-575#17]
Whenever I edit any config, it gives and error and wont load configs

[ERROR] [Exiled.Loader] SCP-575 configs could not be loaded, some of them are in a wrong format, default configs will be loaded instead! YamlDotNet.Core.YamlException: (Line: 45, Col: 7, Idx: 1254) - (Line: 45, Col: 7, Idx: 1254): Exception during deserialization ---> System.InvalidOperationException: Failed to create an instance of type 'Exiled.CustomRoles.API.Features.CustomAbility'. ---> System.MissingMethodException: Default constructor not found for type Exiled.CustomRoles.API.Features.CustomAbility

**Comment by joker-119** [comment]
Yes I know, it will be fixed in EXILED itself.
